### ISSUE TITLE
download version from CRAN does not recognise "tag" argument.

### ISSUE THREAD

**Issue by robsol1** [Enchufa2/simmer#296]

**Comment by robsol1** [comment]
> env <- simmer()
> trj <- trajectory() %>% 
+   log_('This does not work',tag = 'label')
Error in log_(., "This does not work", tag = "label") : 
  unused argument (tag = "label")

this works in the version downloaded from GIT.

Unfortunately I am having trouble installing from GIT on a new windows PC with error message
C:/PROGRA~1/R/R-42~1.3/bin/x64/R.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created

I am not sure how to fix this.

**Comment by Enchufa2** [comment]
Because the CRAN version is 4.4.5, released in June 2022, while the development version here is 4.4.5.2 and includes such a feature (see the [NEWS](https://github.com/r-simmer/simmer/blob/master/NEWS.md)). Currently, we have a yearly release or so, and it's around the end of the academic year, when I have time for this.

About the issue you have installing from GitHub on Windows... do you have RTools installed? The package requires compilation, so RTools is needed to install from source.

**Comment by robsol1** [comment]
Thank you for your quick reply.  I have rtools and MinGW installed and compilation seems to be going ok.   All seems to work on my other computers but just having a lot of difficulty with this install.  I am planning to get one of my students to build some models in simmer and I hope hope he doesn't have the issue. If I understand your calendar it will only be a few months until the CRAN release and hopefully all will be good then.  Thanks again.

**Comment by Enchufa2** [comment]
Yes, meanwhile, the development versions in this organization are compiled for Windows thanks to r-universe: https://r-simmer.r-universe.dev/simmer. Try installing it as follows:

```r
install.packages('simmer', repos = c('https://r-simmer.r-universe.dev', 'https://cloud.r-project.org'))
```

**Comment by robsol1** [comment]
Your a hero, thanks Iñaki.

**Comment by robsol1** [comment]
It works perfectly
